#This is all about me
print("Can you please tell us about your name")
x=input()
print("How old are you")
x=input()
print("What do u study")
x=input()
print("Any favourites?")
x=input()
print("football team?")
x=input()
print("what kind of music taste")
x=input()
print("food?")
x=input()
print("Anything else?")
x=input()
